export const ContentFlowData = [
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: '첫번쨰',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 1,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: '두번째',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 2,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: '세번째',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 3,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 4,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 5,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 6,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 7,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 8,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 9,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 10,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 11,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 12,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 13,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 14,
  },
  {
    avatarSrc: 'https://avatars.githubusercontent.com/u/4512430?v=4',
    avatarName: 'string',
    avatarContent: 'string',
    title: 'string',
    link: '',
    content: 'string',
    id: 15,
  },
];
